imports:
    - { resource: parameters.yml }

framework:
    test: ~
    translator:      { fallback: '%locale%' }
    secret:          '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: true
    default_locale:  '%locale%'
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    php_errors:
        log: true
    profiler: { only_exceptions: false }

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                path:     '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
                server_version: 5.6
            logging: null
            profiling: null
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            # log to var/log/(environment).log
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            # log *all* messages (debug is lowest level)
            level: debug

        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error
